### ISSUE TITLE
(Edge-)Case: Crash while exclusive Access

### ISSUE THREAD

**Issue by Toole-Kartofel** [lmaraite/tcp-server#40]
Wenn ein Client abschmiert, während er exklusiven Zugriff hat, kann die .exclusive Datei nur manuell gelöscht werden.

_Noch nicht behoben, weil heute keine Zeit mehr_

**Comment by Codor77** [comment]
Nennen wir's mal nen EDGECASE...

**Comment by lmaraite** [comment]
ananas
