### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by lmaraite** [lmaraite/tcp-server#51]

**Comment by cvonder1** [comment]
## Design Proposal
There are six levels of logging levels, which each translate into their own function:
1. `TRACE` -> `int trace(const char *msg)` and `int trace(const char *format, ...)`
2. `DEBUG` -> `int debug(const char *msg)` and `int debug(const char *format,  ...)`
3. `INFO` -> `int info(const char *msg)` and `int info(const char *format, ...)`
4. `WARN` -> `int warn(const char *msg)` and `int warn(const char *format, ...)`
5. `ERROR` -> `int error(const char *msg)` and `int error(const char *format, ...)`
  would write to stderr
6. `OFF` -> no corresponding function

For example, if a logging level of `WARN` is set in the configuration, only log messages of `WARN` and `ERROR` will be logged.
These logging levels and function names are inspired by the java [LogBack](http://logback.qos.ch) Logger. This is the default logger in Spring applications.

The logger would go into it's own files `logger.h` and `logger.c`
